layout_spectrum: 1
name: Black Sheep Fitness
typography_spectrum: 0.6711636
color:
  brandStrength: 0.5927488
  saturation: 0.3397976
  brandColors:
    - '#000000'
    - '#F2F2F2'
    - '#808080'
    - '#404040'
    - '#64FD01'
  lightness: 0.2403035
  rhythmicContrast: 0.970489
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
